apiVersion: v1
kind: Service
metadata:
  name: team8-eureka-service-test1
  namespace: group1-team8-test1
spec:
#  type: NodePort # NodePort 타입으로고정 설정
  type: NodePort # 외부에서 접근할 수 있는 IP 주소가 할당
  selector:
    app: eureka-team8-test1 # Deployment와 연결되는 selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 30856
