apiVersion: apps/v1 # 필수 표준 apps/v1
kind: Deployment
metadata:
  name: eureka-team8-test1
  namespace: group1-team8-test1
  labels:
    app: eureka-team8-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-team8-test1
  template:
    metadata:
      labels:
        app: eureka-team8-test1
    spec:
      containers:
      - name: eureka-team8-test1
        image: k8s-vga-worker1:5000/eureka-team8-test1:latest
        ports:
        - containerPort: 8761
